fix: Fix compile_pip_requirements for our use case
bazelbuild/rules_python pull request #1131
Opened 2023-03-14 17:11 UTC by blorente

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [X] Build related changes

## What is the current behavior?

`compile_pip_requirements`:
- Forced the `no-remote-exec` tag on all its users, conflicting with our current toolchain + RBE setup.
- Use `shutil.copy` to copy files around. While this works for the current script, it broke in our remote execution enviornment, since it tries to open the destination file for writing.

## What is the new behavior?

- Make the tags optional. I chose to implement them as an overridable default because it more closer resembles the current implementation, but I think there is latitude to make some required (e.g. `requires-network`) and some optional (`no-remote-exec`).
- `shutil.move` can move files across namespaces, and preserves the semantics of `os.replace` better.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2023-03-15 00:33 UTC, aignas commented
It looks like you still need to update the docs via `bazel run //docs:update` to fix the build failures.

2023-03-15 01:00 UTC, hrfuller commented
The change seems benign, but looking closer those tags seem to only apply to the generated `_test` target, unless the binary is used as a tool in an action elsewhere, so maybe those can be added to the test tags only. @f0rmiga do you remember if the no-sandbox and no-remote-exec tags were needed for the updater binary?

2023-03-16 02:18 UTC, f0rmiga commented
I'll have to dig the history to remember the details.

2023-04-24 16:05 UTC, chrislovecnm requested changes

2023-04-24 16:05 UTC, chrislovecnm commented on python/pip_install/tools/dependency_resolver/dependency_resolver.py
> +os.replace = shutil.move
Dumb question.  Do we have a use-case where we would need the files you moved?

2023-04-24 16:05 UTC, chrislovecnm commented on python/pip_install/requirements.bzl
> +        tags = _DEFAULT_TAGS,
Adding defaults makes sense if we always need defaults, but I wonder if we always do. I would like to see documentation on our defaults and how to override them.  Is there a creative way to do this without adding defaults?

2023-11-20 22:50 UTC, closed without merging