fix(transitions): correctly default 'main' arg for transition rules
bazelbuild/rules_python pull request #1316
Opened 2023-07-14 08:37 UTC by aignas

Before the change the version-aware py_binary and py_test rules would
not default the 'main' argument correctly and this change adds unit
tests and a helper function to do the defaulting.

Work towards #1262

2023-07-14 17:34 UTC, rickeylev commented
Some fun trivia about how py_binary finds main: it's basically a suffix search. e.g.

```
search_for = name + ".py"
main = None
for src in srcs:
  if src.endswith(search_for):
    main = None
    break
```

2023-07-14 17:35 UTC, rickeylev requested changes
Mostly lgtm, but one bug to fix and some nits

2023-07-14 17:35 UTC, rickeylev commented on python/extensions/private/defs.bzl.tmpl
I don't see this used anywhere -- I'm guessing this leaked over from your other PR? Please remove

2023-07-14 17:35 UTC, rickeylev commented on python/config_settings/private/py_args.bzl
> +        main = kwargs.pop("main", name),
```suggestion
        # See https://bazel.build/reference/be/python#py_binary.main
        # for default logic.
        # NOTE: This doesn't match the exact way a regular py_binary searches for
        # it's main amongst the srcs, but is close enough for most cases.
        main = kwargs.pop("main", name),
```

2023-07-14 17:35 UTC, rickeylev commented on python/config_settings/private/py_args.bzl
> +        kwargs: The kwargs to be extracted from.
```suggestion
        kwargs: The kwargs to be extracted from; MODIFIED IN-PLACE
```

2023-07-14 17:35 UTC, rickeylev commented on tests/config_settings/transition/py_args_tests.bzl
> +        "main": "foo",
Main should be a .py file, i.e. name + ".py" -- please fix.

I'm surprised this didn't didn't cause a failure somewhere. When given an explicit main, the py_binary should have failed when it tried to look for a non-existent file with the same name as itself

2023-07-14 17:35 UTC, rickeylev commented on tests/config_settings/transition/py_args_tests.bzl
> +    env.expect.that_dict(kwargs).keys().contains_exactly(["visibility"])
Also check that kwargs doesn't contain one of the keys, to verify that it is modified in place.

2023-07-15 03:27 UTC, aignas commented
@rickeylev, yeah, the fact that `main` parameter does not have to be a string ending with `.py` suffix also surprised me.

As for the comment about modification in place test, it is there already because the `contains_exactly` is used for assertions. Tested this by adding an extra `kwarg` (e.g. `tags`) into the input and the expectation started failing.

2023-07-20 02:27 UTC, rickeylev approved these changes

2023-07-20 02:38 UTC, merged