refactor(whl_library): move bazel file generation to Starlark
bazelbuild/rules_python pull request #1336
Opened 2023-07-22 03:23 UTC by aignas

Before this PR, the `wheel_installer` was doing three things:
1. Downloading the right wheel.
2. Extracting it into the output directory.
3. Generating BUILD.bazel files based on the extracted contents.

This PR is moving the third part into the `whl_library` repository rule
and it has the following benefits:
* We can reduce code duplication and label sanitization functions in
  rules_python.
* There are many things that the `wheel_installer` does not care anymore
  and we don't need to change less code when extending `whl_library` as
  we can now do many things in starlark directly.
* It becomes easier to change the API of how we expose the generated
  BUILD.bazel patching because we only need to change the Starlark
  functions.

Work towards #1330.

2023-07-22 03:42 UTC, aignas commented
FYI @chrislovecnm, I decided to see how this idea of generating BUILD.bazel and other extra files worked out in reality and I think I am happy with the solution. It makes working on the #1262 and extending the API easier, hence me doing this refactor before extending the `whl_library` more.

2023-07-31 21:49 UTC, rickeylev requested changes
Mostly lgtm

2023-07-31 21:49 UTC, rickeylev commented on python/pip_install/private/generate_whl_library_build_bazel.bzl
> +        allow_empty = True,
```suggestion
        # Empty sources are allowed to support wheels that don't have any
        # pure-Python code, e.g. pymssql, which is written in Cython.
        allow_empty = True,
```

2023-07-31 21:49 UTC, rickeylev commented on python/pip_install/private/generate_whl_library_build_bazel.bzl
> +    there may be no Python sources whatsoever (e.g. packages written in Cython: like `pymssql`).
nit: move the comment inline where the allow_empty setting is actually used (see the other suggested edit)

```suggestion
```

2023-07-31 21:49 UTC, rickeylev commented on python/pip_install/private/generate_whl_library_build_bazel.bzl
> +            _generate_entry_point_rule(
nit: use named args for this call.

2023-07-31 21:49 UTC, rickeylev commented on python/pip_install/private/generate_whl_library_build_bazel.bzl
> +        src = str(script).replace("\\", "/"),
This str() call looks unnecessary? The input is already a string, no?

2023-08-02 16:16 UTC, rickeylev approved these changes

2023-08-02 16:23 UTC, merged