feat: Add s390x release
bazelbuild/rules_python pull request #1352
Opened 2023-08-01 05:39 UTC by namrata-ibm

Include s390x in release and update python-build-standalone to 3.9.17, 3.10.12, 3.11.4.
[Latest python-build-standalone release](https://github.com/indygreg/python-build-standalone/releases/tag/20230726) has s390x support added.

These changes are needed to build TensorFlow on s390x, which is currently blocked due to missing support.

2023-08-01 08:48 UTC, aignas commented
@namrata-ibm, #1340 should fix what you mention in your message, then we would only have `3.11:defs.bzl` instead of `3.11.1:defs.bzl`. That said, it would be fixing it only for `bzlmod` and for traditional workspaces we would likely need to do additional fixes.

2023-08-01 09:12 UTC, namrata-ibm commented
Thank you @aignas for pointing out. 
Will check #1340 for further updates. If it is ongoing work and might take longer, then I can revert the MINOR_MAPPING changes from this PR. 
However it would be good to have, to avoid explicit python version setting(eg in TensorFlow) during build on s390x.

2023-08-01 13:27 UTC, aignas commented
I think the minor mapping changes are good and they should stay in this PR,
if any other code is broken, it should be fixed.

On Tue, 1 Aug 2023, 18:12 Namrata Bhave, ***@***.***> wrote:

> Thank you @aignas <https://github.com/aignas> for pointing out.
> Will check #1340 <https://github.com/bazelbuild/rules_python/pull/1340>
> for further updates. If it is ongoing work and might take longer, then I
> can revert the MINOR_MAPPING changes from this PR.
> However it would be good to have, to avoid explicit python version
> setting(eg in TensorFlow) during build on s390x.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_python/pull/1352#issuecomment-1659904010>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB22KVIXRBISSLHB2I3H43XTDB7TANCNFSM6AAAAAA27G6IVE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-03 19:03 UTC, chrislovecnm commented
@namrata-ibm please take a look at CI/CD failures: https://buildkite.com/bazel/rules-python-python/builds/5380#0189af9c-468d-4b55-ac85-9954d0197118

2023-08-04 06:16 UTC, namrata-ibm commented
@chrislovecnm Thank you for checking, all the CI failures are same and addressed in above [comments](https://github.com/bazelbuild/rules_python/pull/1352#issuecomment-1659721946). It would be great to hear comments about the queries listed up.

2023-08-04 09:14 UTC, aignas commented
@namrata-ibm, could you see if you can fix the WORKSPACE with the expected command please? Replacing `3.11.1` with `3.11.4` everywhere would be good enough.

2023-08-04 10:01 UTC, namrata-ibm commented
@aignas I added the WORKSPACE change and all earlier failures have passed in latest run. However I see `Buildifier` failed with 1 format issue. I tried running `buildifier python/versions.bzl` with v6.1.0 , however I do not see any error. Could you please help?

2023-08-05 02:17 UTC, aignas commented
@namrata-ibm, this looks like a CI flake.

2023-08-05 14:31 UTC, chrislovecnm commented
> @namrata-ibm, this looks like a CI flake.

@aignas did we hit a bug in buildifier?

2023-08-07 09:47 UTC, namrata-ibm commented
@aignas @chrislovecnm @rickeylev could you please provide your inputs on how to proceed further?
Thank you.

2023-08-07 15:26 UTC, chrislovecnm requested changes
Thanks for the PR. Please run `buildifier` to get CI passing.  I think we should have two PRs here.

1. include support for the new Python versions and support for `s390x`. 
2. after that PR bump the mappings to increase the default version numbers

2023-08-07 15:26 UTC, chrislovecnm commented on python/versions.bzl
> +    "3.9.17": {
@rickeylev @aignas any other Python versions that we should have `s390x` support for?

2023-08-08 09:29 UTC, namrata-ibm commented
@chrislovecnm Thank you, I have updated this PR to keep only s390x and python version updates.
Will raise PR for Minor mapping changes later.

Could you please check and help merge this?

2023-08-08 14:49 UTC, merged