build(deps): Bump pip tools to >= 7.4.0
bazelbuild/rules_python pull request #1841
Opened 2024-04-11 18:18 UTC by dougthor42

Bump pip_tools to >= 7.4.0 so that we can make use of better
`pyproject.toml` parsing error messages during compiling.

Specifically: https://github.com/jazzband/pip-tools/pull/1979

2024-04-11 18:21 UTC, dougthor42 commented on python/pip_install/repositories.bzl
> +        "https://files.pythonhosted.org/packages/e2/03/f3c8ba0a6b6e30d7d18c40faab90807c9bb5e9a1e3b2fe2008af624a9c97/build-1.2.1-py3-none-any.whl",
`pip_tools` v7.4.0 (coincidentlaly, the same https://github.com/jazzband/pip-tools/pull/1979 that I'm interested in using) also pinned `build >= 1.0.0`. In `pip_tools <= 7.3.0`, `build` did not have any version specifier.

2024-04-17 06:45 UTC, aignas requested changes
Please include the changes to the CHANGELOG.md.

2024-04-17 17:55 UTC, dougthor42 commented
😱 Oops, I'm really bad at remembering to do that. Sorry! Updated.

I also noticed that there were two "Changed" sections so I merged them.

2024-04-18 01:00 UTC, aignas approved these changes
LGTM

2024-04-18 01:09 UTC, merged