feat(toolchain): Add support for Python 3.13.1.
bazelbuild/rules_python pull request #2482
Opened 2024-12-06 18:00 UTC by okin

Adds 3.13.1 Python toolchain.

Also updates 3.13 to map to 3.13.1.

Tests have been slightly altered to make spotting the override easier.

2024-12-07 00:11 UTC, aignas requested changes
Thanks for the PR!

Please add other versions for the toolchains from the latest release and use the [20241206](https://github.com/indygreg/python-build-standalone/releases/tag/20241206) release.

That means:
* CPython 3.9.20 -> 3.9.21
* CPython 3.10.15 -> 3.10.16
* CPython 3.11.10 -> 3.11.11
* CPython 3.12.7 -> 3.12.8
* CPython 3.13.0 -> 3.13.1

Also please add a note to the CHANGELOG.md just like it was done for previous releases.

2024-12-07 22:20 UTC, rickeylev commented
Thanks for the PR!

I pushed an update for the changelog for the 3.13.1 part and synced this to head.

2024-12-20 08:45 UTC, aignas commented on CHANGELOG.md
> +    * 3.12.8
```suggestion
  Fixes [#2386](https://github.com/bazelbuild/rules_python/issues/2386).
* (toolchains) Use the latest astrahl-sh toolchain release [20241206] for Python versions:
    * 3.9.21
    * 3.10.16
    * 3.11.11
    * 3.12.8
    * 3.13.1
```

Technically speaking these are new versions, so we can just lump the changelog entries.

2024-12-24 00:33 UTC, aignas approved these changes

2024-12-24 00:33 UTC, aignas commented
Thank you!

2024-12-24 00:50 UTC, merged