feat: allow setting custom environment variables on pip_repository and whl_library
bazelbuild/rules_python pull request #460
Opened 2021-04-19 16:00 UTC by mattem

Allows specifying custom environment variables on the pip_repository and whl_library repository rules that are set when run.

2021-04-19 18:37 UTC, mattem commented
cc @alexeagle 🌮

2021-04-19 20:33 UTC, alexeagle commented on python/pip_install/pip_repository.bzl
> +        doc = """Environment variables to set before calling the package manager.""",
nit: maybe mention which ones are typical to set, so users know that this might be what solves their problem?

2021-04-19 20:33 UTC, alexeagle approved these changes

2021-04-23 04:02 UTC, hrfuller requested changes
In order for this to work with pip_parse the  rctx.attr.environment needs to be serialized,see `_parse_optional_attrs`, and passed into the `parse_requirements_to_bzl` script via a command line arg. It should then be deserialized and written to the requirements.bzl file that is produced by that script. That will make all the whl_library subrepos that depend on a pip_parse repo will use the environment.

2021-07-25 21:19 UTC, hrfuller commented
@googlebot I consent.

2021-07-25 21:32 UTC, hrfuller approved these changes

2021-07-25 23:28 UTC, hrfuller commented
Hey @mattem I have tested this using an HTTPS_PROXY env var in the pip_parse example, and it works. Would you like to wait for review from @andyscott / @alexeagle  before I merge?

2021-07-29 21:54 UTC, mattem commented
Thanks for pushing this over the line @hrfuller! I think this is okay, I'm happy for it to be merged though.

2021-07-30 05:39 UTC, merged