feat: add requires_file attr for py_wheel
bazelbuild/rules_python pull request #644
Opened 2022-03-08 20:38 UTC by weixiao-huang

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-03-13 11:38 UTC, pstradomski commented
Any background for why this is needed? Maybe the documentation should be updated to reflect that and what's the interaction with "requires" attribute?

2022-03-13 12:00 UTC, weixiao-huang commented
Because sometimes we may write codes like this in `setup.py`

```python
#!/usr/bin/env python

from setuptools import setup, find_packages

with open("requirements.txt") as fp:
    install_requires = fp.read()


setup(
    # get requires from file
    install_requires=install_requires,
)
```

However, in `py_wheel`, it only provides requires from bazel string. It seems we cannot get requires from files. So I add `requires_file` in `py_wheel`.

If `requires` specified, `requires_file` will not work

2022-09-10 02:26 UTC, weixiao-huang commented
Is there any update of this PR?

2022-10-10 17:13 UTC, UebelAndre commented
@weixiao-huang would you be able to rebase this and address conflicts?

2022-10-11 15:25 UTC, UebelAndre requested changes
I'm no maintainer but did have some requests 😅

2022-10-11 15:25 UTC, UebelAndre commented on python/packaging.bzl
> +    if len(ctx.attr.requires) == 0 and ctx.attr.requires_file:
Would it be possible to make this additive?

2022-10-11 15:25 UTC, UebelAndre commented on tools/wheelmaker.py
> +        default="",
I don't think there's a need to set a default here.

2022-10-11 15:25 UTC, UebelAndre commented on tools/wheelmaker.py
> +            with open(arguments.requires_file) as fp:
Shouldn't this instead be written to `Requires-Dist:` in the metadata? My use case for this is to be able to define 3rdparty dependencies in `requirements.in` files and be able to continue to use the existing `requires` field for local dependencies.

2022-10-13 18:37 UTC, pstradomski commented on tools/wheelmaker.py
> +                metadata += "\n" + "\n".join(additive_requires_list)
Won't that leave you with two \n in a row, so everything below will be interpreted as description?

Can we have a test?

2022-10-13 18:37 UTC, pstradomski commented on tools/wheelmaker.py
> +                additive_requires_list = ["Requires-Dist: {}".format(line) for line in fp.read().strip().split("\n")]
why read().strip().split() and not readlines()?

2023-04-24 16:16 UTC, chrislovecnm commented
@weixiao-huang knudge

2023-04-25 09:33 UTC, weixiao-huang commented
Sorry, I'll check it recently

2023-11-21 22:50 UTC, closed without merging