breaking: feat(gazelle): Move the plugin to a separate workspace
bazelbuild/rules_python pull request #972
Opened 2023-01-04 07:29 UTC by aignas

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Previously the gazelle plugin was part of the same `WORKSPACE`. This means that we cannot have a separate `bzlmod` module and make the `rules_python` repo work with both, `bzlmod` and legacy dependency management systems.

Issue Number: #965

## What is the new behavior?

The `gazelle` plugin is now isolated with its own `WORKSPACE` file. Whilst making this I have also moved the plugin source code to a separate directory.

Summary:
- Move go.mod to gazelle.
- Move `gazelle` definition.
- Move the gazelle plugin to a separate folder, just like `bazel-skylib` does, which helps with naming of the externally visible targets.
- Fix file `distribution` for the gazelle module.
- Update the example test.
- Include rules_python_gazelle_plugin during integration tests
- Update ignored packages

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

Steps that need to be taken:
- Add a new dependency to your `WORKSPACE` and change the import path for the plugin dependency setup.
- If you are using the gazelle binary from the plugin repo, use the new label `@rules_python_gazelle_plugin//python:gazelle_binary`.
- If you are using the gazelle language extension, use the new label `@rules_python_gazelle_plugin//python`.
- `gazelle_python.yaml` integrity gets changed for all users.

2023-01-04 16:17 UTC, chrislovecnm requested changes
Look great.  I have some nitpicks that I noticed, but I like it!!  Working on the build_file_generation example I was wondering if bzmod and gazelle where working.

2023-01-04 16:17 UTC, chrislovecnm commented on .bazelrc
> +build --deleted_packages=examples/build_file_generation,examples/build_file_generation/random_number_generator,examples/bzlmod,examples/multi_python_versions,examples/multi_python_versions/libs/my_li
This is fixing a bug that I missed that is outside the scope of this PR.  Can we do this in a different PR?

2023-01-04 16:17 UTC, chrislovecnm commented on examples/build_file_generation/WORKSPACE
> +local_repository(
Can we add a comment on what local_repository does and how you don't want to use it when you create your own project?

2023-01-04 16:17 UTC, chrislovecnm commented on gazelle/.gitignore
> +# Compiled Object files
Do we need this here?  Don't we have an ignore file in the root directory?

2023-01-04 16:17 UTC, chrislovecnm commented on gazelle/python/python_test.go
> +	extensionDir      = "python/"
Should we use ` os.PathSeparator` here?

2023-01-10 18:32 UTC, alexeagle commented
FYI @f0rmiga is on paternity leave, back next week I believe

2023-01-10 18:50 UTC, chrislovecnm commented
@alexeagle who else can review it?

2023-01-11 18:28 UTC, alexeagle commented
I think we should probably just wait for @f0rmiga to be back. This will need someone to invest a few hours.

As one way to make this easier to land, @aignas is it possible to split out a separate PR that does the directory rename so this doesn't show as a 433 files changed? I can't even get started on reviewing it at this size without setting aside a chunk of my day.

2023-01-12 02:45 UTC, aignas commented
Hey @alexeagle, I also think that waiting for @f0rmiga is probably for the best. I can split it to several commits at the very least. I think the rename is necessary to make everything work as we are moving the `gazelle` rule usage to the `gazelle` folder and it makes things a little bit tricky.

What I can do to make it easier to review is to split it into multiple PRs introducing a breaking change:
* Do the folder rename.
* Add a new WORKSPACE.
* Whatever is left afterwards.

How does it sound to you?

2023-01-12 04:19 UTC, alexeagle commented
Yeah I think the folder rename first will make it more manageable. Thanks!

2023-01-24 06:34 UTC, aignas commented
@f0rmiga, I think once you merge #983, this PR should be much more approachable.

2023-01-25 19:20 UTC, f0rmiga approved these changes

2023-01-25 19:20 UTC, merged

2023-01-25 19:20 UTC, f0rmiga commented
Thanks for addressing this, @aignas!